# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PictureDiary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PictureDiary

	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~> 3.8'
	pod 'ELCImagePickerController', '~> 0.2'
end
